name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use GitHub Actions token
        run: |
          echo "GitHub Actions token: ${{ secrets.GITHUB_TOKEN }}"
